// export const NETWORKS = {
//     ethereum: {
//       name: "Ethereum",
//       rpcUrl: "https://mainnet.infura.io/v3/e33cecb12ec3492bba4f0972afcfc4fa",
//       explorerUrl: "https://etherscan.io",
//       currency: "ETH",
//     },
//     polygon: {
//       name: "Polygon",
//       rpcUrl: "https://polygon-mainnet.infura.io/v3/e33cecb12ec3492bba4f0972afcfc4fa",
//       explorerUrl: "https://polygonscan.com",
//       currency: "MATIC",
//     },
//     bsc: {
//       name: "Binance Smart Chain",
//       rpcUrl: "https://bsc-mainnet.infura.io/v3/e33cecb12ec3492bba4f0972afcfc4fa",
//       explorerUrl: "https://bscscan.com",
//       currency: "BNB",
//     },
//     sepolia: {
//       name: "Sepolia (Testnet)",
//       rpcUrl: "https://sepolia.infura.io/v3/e33cecb12ec3492bba4f0972afcfc4fa",
//       explorerUrl: "https://sepolia.etherscan.io",
//       currency: "ETH",
//     },
//   };

export const NETWORKS = {
    ethereum: {
      name: "Ethereum",
      rpcUrl: "https://mainnet.infura.io/v3/e33cecb12ec3492bba4f0972afcfc4fa",
      explorerUrl: "https://etherscan.io",
      currency: "ETH",
      icon: "https://cryptologos.cc/logos/ethereum-eth-logo.png",
      theme: {
        background: "bg-blue-50",
        text: "text-blue-900",
        cardBackground: "bg-white",
        selectBorder: "border-blue-300",
        selectFocus: "focus:ring-blue-500",
        inputBorder: "border-blue-300",
        inputFocus: "focus:ring-blue-500",
        buttonBackground: "bg-blue-500 text-white",
        buttonHover: "hover:bg-blue-600",
      },
    },
    polygon: {
      name: "Polygon",
      rpcUrl: "https://polygon-mainnet.infura.io/v3/e33cecb12ec3492bba4f0972afcfc4fa",
      explorerUrl: "https://polygonscan.com",
      currency: "MATIC",
      icon: "https://cryptologos.cc/logos/polygon-matic-logo.png",
      theme: {
        background: "bg-purple-50",
        text: "text-purple-900",
        cardBackground: "bg-white",
        selectBorder: "border-purple-300",
        selectFocus: "focus:ring-purple-500",
        inputBorder: "border-purple-300",
        inputFocus: "focus:ring-purple-500",
        buttonBackground: "bg-purple-500 text-white",
        buttonHover: "hover:bg-purple-600",
      },
    },
    bsc: {
      name: "Binance Smart Chain",
      rpcUrl:"https://bsc-mainnet.infura.io/v3/e33cecb12ec3492bba4f0972afcfc4fa",
      explorerUrl: "https://bscscan.com",
      currency: "BNB",
      icon: "https://cryptologos.cc/logos/binance-coin-bnb-logo.png",
      theme: {
        background: "bg-yellow-50",
        text: "text-yellow-900",
        cardBackground: "bg-white",
        selectBorder: "border-yellow-300",
        selectFocus: "focus:ring-yellow-500",
        inputBorder: "border-yellow-300",
        inputFocus: "focus:ring-yellow-500",
        buttonBackground: "bg-yellow-500 text-white",
        buttonHover: "hover:bg-yellow-600",
      },
    },
    sepolia: {
      name: "Sepolia (Testnet)",
      rpcUrl: "https://sepolia.infura.io/v3/e33cecb12ec3492bba4f0972afcfc4fa",
      explorerUrl: "https://sepolia.etherscan.io",
      currency: "ETH",
      icon: "https://cryptologos.cc/logos/ethereum-eth-logo.png",
      theme: {
        background: "bg-blue-50",
        text: "text-blue-900",
        cardBackground: "bg-white",
        selectBorder: "border-blue-300",
        selectFocus: "focus:ring-blue-500",
        inputBorder: "border-blue-300",
        inputFocus: "focus:ring-blue-500",
        buttonBackground: "bg-blue-500 text-white",
        buttonHover: "hover:bg-blue-600",
      },
    },
  };